// <auto-generated />
using System;
using EFC_Project.App_Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFC_Project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714043943_ReStart")]
    partial class ReStart
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFC_Project.Models.Account", b =>
                {
                    b.Property<int>("AccountNumber")
                        .HasColumnType("int");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BranchCode")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OpeningDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AccountNumber");

                    b.HasIndex("BranchCode");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountNumber = 1001,
                            AccountType = "Savings",
                            BranchCode = 1,
                            CurrentBalance = 15500.00m,
                            OpeningDate = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AccountNumber = 1002,
                            AccountType = "Current",
                            BranchCode = 1,
                            CurrentBalance = 8200.50m,
                            OpeningDate = new DateTime(2022, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AccountNumber = 1003,
                            AccountType = "Business",
                            BranchCode = 2,
                            CurrentBalance = 250000.00m,
                            OpeningDate = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AccountNumber = 1004,
                            AccountType = "Savings",
                            BranchCode = 3,
                            CurrentBalance = 5000.00m,
                            OpeningDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AccountNumber = 1005,
                            AccountType = "Current",
                            BranchCode = 2,
                            CurrentBalance = 30250.75m,
                            OpeningDate = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("EFC_Project.Models.Branch", b =>
                {
                    b.Property<int>("BranchCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchCode"));

                    b.Property<string>("BranchAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BranchCode");

                    b.ToTable("Branches", (string)null);

                    b.HasData(
                        new
                        {
                            BranchCode = 1,
                            BranchAddress = "12 Corniche St, Alexandria",
                            BranchName = "Alexandria Main",
                            BranchPhoneNumber = "0345678901"
                        },
                        new
                        {
                            BranchCode = 2,
                            BranchAddress = "45 Tahrir Sq, Cairo",
                            BranchName = "Cairo Downtown",
                            BranchPhoneNumber = "0223456789"
                        },
                        new
                        {
                            BranchCode = 3,
                            BranchAddress = "8 Pyramids Rd, Giza",
                            BranchName = "Giza Branch",
                            BranchPhoneNumber = "0233445566"
                        });
                });

            modelBuilder.Entity("EFC_Project.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CustomerDateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerNationalID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerType")
                        .HasColumnType("int");

                    b.HasKey("CustomerID");

                    b.HasIndex("CustomerEmailAddress")
                        .IsUnique();

                    b.HasIndex("CustomerNationalID")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            CustomerAddress = "3 Smouha St, Alexandria",
                            CustomerDateOfBirth = new DateTime(1995, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerEmailAddress = "youssef.hany@mail.com",
                            CustomerFullName = "Youssef Hany",
                            CustomerNationalID = "29505121234567",
                            CustomerPhoneNumber = "01055512345",
                            CustomerType = 1
                        },
                        new
                        {
                            CustomerID = 2,
                            CustomerAddress = "7 Sidi Gaber, Alexandria",
                            CustomerDateOfBirth = new DateTime(1990, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerEmailAddress = "nour.tarek@mail.com",
                            CustomerFullName = "Nour ElDin Tarek",
                            CustomerNationalID = "29011031234567",
                            CustomerPhoneNumber = "01166654321",
                            CustomerType = 1
                        },
                        new
                        {
                            CustomerID = 3,
                            CustomerAddress = "22 Nasr City, Cairo",
                            CustomerDateOfBirth = new DateTime(2005, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerEmailAddress = "contact@deltatrading.com",
                            CustomerFullName = "Delta Trading Co.",
                            CustomerNationalID = "10000000000001",
                            CustomerPhoneNumber = "0224455667",
                            CustomerType = 2
                        },
                        new
                        {
                            CustomerID = 4,
                            CustomerAddress = "5 Dokki, Giza",
                            CustomerDateOfBirth = new DateTime(1998, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerEmailAddress = "salma.reda@mail.com",
                            CustomerFullName = "Salma Reda",
                            CustomerNationalID = "29808221234567",
                            CustomerPhoneNumber = "01234567890",
                            CustomerType = 1
                        },
                        new
                        {
                            CustomerID = 5,
                            CustomerAddress = "9 Agouza, Giza",
                            CustomerDateOfBirth = new DateTime(1988, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerEmailAddress = "omar.fathy@mail.com",
                            CustomerFullName = "Omar Fathy",
                            CustomerNationalID = "28804091234567",
                            CustomerPhoneNumber = "01187654321",
                            CustomerType = 1
                        });
                });

            modelBuilder.Entity("EFC_Project.Models.CustomerAccount", b =>
                {
                    b.Property<int>("AccountNumber")
                        .HasColumnType("int");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("AccountStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("OwnerShipStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OwnerShipType")
                        .HasColumnType("int");

                    b.HasKey("AccountNumber", "CustomerID");

                    b.HasIndex("CustomerID");

                    b.ToTable("CustomerAccounts");

                    b.HasData(
                        new
                        {
                            AccountNumber = 1001,
                            CustomerID = 1,
                            AccountStatus = 1,
                            OwnerShipStartDate = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerShipType = 1
                        },
                        new
                        {
                            AccountNumber = 1002,
                            CustomerID = 1,
                            AccountStatus = 1,
                            OwnerShipStartDate = new DateTime(2022, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerShipType = 1
                        },
                        new
                        {
                            AccountNumber = 1003,
                            CustomerID = 3,
                            AccountStatus = 1,
                            OwnerShipStartDate = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerShipType = 1
                        },
                        new
                        {
                            AccountNumber = 1003,
                            CustomerID = 4,
                            AccountStatus = 1,
                            OwnerShipStartDate = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerShipType = 2
                        },
                        new
                        {
                            AccountNumber = 1004,
                            CustomerID = 4,
                            AccountStatus = 1,
                            OwnerShipStartDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerShipType = 1
                        },
                        new
                        {
                            AccountNumber = 1005,
                            CustomerID = 5,
                            AccountStatus = 2,
                            OwnerShipStartDate = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerShipType = 1
                        });
                });

            modelBuilder.Entity("EFC_Project.Models.Manager", b =>
                {
                    b.Property<int>("ManagerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManagerID"));

                    b.Property<int>("BranchCode")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ManagerFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ManagerID");

                    b.HasIndex("BranchCode")
                        .IsUnique();

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.ToTable("Managers", (string)null);

                    b.HasData(
                        new
                        {
                            ManagerID = 1,
                            BranchCode = 1,
                            EmailAddress = "ahmed.salah@natbank.com",
                            HireDate = new DateTime(2019, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManagerFullName = "Ahmed Salah",
                            ManagerPhoneNumber = "01012345678"
                        },
                        new
                        {
                            ManagerID = 2,
                            BranchCode = 2,
                            EmailAddress = "mona.farouk@natbank.com",
                            HireDate = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManagerFullName = "Mona Farouk",
                            ManagerPhoneNumber = "01098765432"
                        },
                        new
                        {
                            ManagerID = 3,
                            BranchCode = 3,
                            EmailAddress = "karim.adel@natbank.com",
                            HireDate = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManagerFullName = "Karim Adel",
                            ManagerPhoneNumber = "01123456789"
                        });
                });

            modelBuilder.Entity("EFC_Project.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionNumber"));

                    b.Property<int>("AccountNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("TransactionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionNote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionNumber");

                    b.HasIndex("AccountNumber");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionNumber = 1,
                            AccountNumber = 1001,
                            TransactionAmount = 2000.00m,
                            TransactionDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionNote = "Salary deposit",
                            TransactionType = "Deposit"
                        },
                        new
                        {
                            TransactionNumber = 2,
                            AccountNumber = 1001,
                            TransactionAmount = 500.00m,
                            TransactionDate = new DateTime(2024, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionNote = "ATM withdrawal",
                            TransactionType = "Withdrawal"
                        },
                        new
                        {
                            TransactionNumber = 3,
                            AccountNumber = 1002,
                            TransactionAmount = 1200.50m,
                            TransactionDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionNote = "Utility bill",
                            TransactionType = "Payment"
                        },
                        new
                        {
                            TransactionNumber = 4,
                            AccountNumber = 1003,
                            TransactionAmount = 50000.00m,
                            TransactionDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionNote = "Client payment received",
                            TransactionType = "Deposit"
                        },
                        new
                        {
                            TransactionNumber = 5,
                            AccountNumber = 1003,
                            TransactionAmount = 10000.00m,
                            TransactionDate = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionNote = "Transfer to supplier",
                            TransactionType = "Transfer"
                        },
                        new
                        {
                            TransactionNumber = 6,
                            AccountNumber = 1004,
                            TransactionAmount = 1000.00m,
                            TransactionDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionNote = "Cash deposit",
                            TransactionType = "Deposit"
                        },
                        new
                        {
                            TransactionNumber = 7,
                            AccountNumber = 1005,
                            TransactionAmount = 250.75m,
                            TransactionDate = new DateTime(2024, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionNote = "Grocery shopping",
                            TransactionType = "Withdrawal"
                        });
                });

            modelBuilder.Entity("EFC_Project.Models.Account", b =>
                {
                    b.HasOne("EFC_Project.Models.Branch", "Branch")
                        .WithMany("Accounts")
                        .HasForeignKey("BranchCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("EFC_Project.Models.CustomerAccount", b =>
                {
                    b.HasOne("EFC_Project.Models.Account", "Account")
                        .WithMany("CustomerAccounts")
                        .HasForeignKey("AccountNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFC_Project.Models.Customer", "Customer")
                        .WithMany("CustomerAccounts")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("EFC_Project.Models.Manager", b =>
                {
                    b.HasOne("EFC_Project.Models.Branch", "ManagerBranch")
                        .WithOne("Manager")
                        .HasForeignKey("EFC_Project.Models.Manager", "BranchCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManagerBranch");
                });

            modelBuilder.Entity("EFC_Project.Models.Transaction", b =>
                {
                    b.HasOne("EFC_Project.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("EFC_Project.Models.Account", b =>
                {
                    b.Navigation("CustomerAccounts");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("EFC_Project.Models.Branch", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Manager")
                        .IsRequired();
                });

            modelBuilder.Entity("EFC_Project.Models.Customer", b =>
                {
                    b.Navigation("CustomerAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
